[
    uuid(7dcb4680-4e4f-4b25-a9ab-4f6d2f6dbd5a),
    version(1.0)
]
interface BmtxRpc
{
    typedef struct _BMTX_CLIENT_STATE
    {
        long authenticated;
        long licensed;
        long antivirusEnabled;
        hyper licenseExpiresAtUnix;
        wchar_t username[128];
        wchar_t message[256];
    } BMTX_CLIENT_STATE;

    void BmtxStopService([in] handle_t Binding);
    unsigned long BmtxGetClientState([in] handle_t Binding, [out] BMTX_CLIENT_STATE* State);
    unsigned long BmtxLogin([in] handle_t Binding, [in, string] wchar_t* Username, [in, string] wchar_t* Password, [out] BMTX_CLIENT_STATE* State);
    unsigned long BmtxLogout([in] handle_t Binding, [out] BMTX_CLIENT_STATE* State);
    unsigned long BmtxActivateProduct([in] handle_t Binding, [in, string] wchar_t* ActivationCode, [out] BMTX_CLIENT_STATE* State);
    unsigned long BmtxRefreshLicenseState([in] handle_t Binding, [out] BMTX_CLIENT_STATE* State);
}
